site_name: Adrien Durier
site_url: "https://adurier.github.io/"
# Empty for local (or multiple domain?) use. Otherwise, use https://adurier.github.io/ or...

nav:
  - Home: 'index.md'
  - Enseignement: 
#    - 'teaching/index.md'
    - Enseignements passés: 'teaching/teaching.md'
    - Cours de Logique: 'https://adurier.github.io/logic-course'
    - Cours de Programmation Fonctionnelle: 'https://adurier.github.io/func-prog'
  - Publications: 'publis.md'
  - A propos: 'about.md' 

not_in_nav: |
  /helper.md

theme:
    name: 'dracula'
    logo: assets/logo.png
    icon:
      repo: fontawesome/brands/git-alt

# Extensions
markdown_extensions:
  - nl2br
  - footnotes
  - admonition
  - abbr
  - md_in_html
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
# - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#  - toc:
#      permalink: true
      
repo_url: https://github.com/adurier/adurier.github.io
extra:
  social:
  - icon: fontawesome/brands/github 
    link: https://github.com/adurier

plugins:
#  - search
#  - roamlinks
  - obsidian-bridge
  - callouts

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
