nav:
  - Home: 'index.md'
  - Enseignement: 
#    - 'teaching/index.md'
    - Enseignements passés: 'teaching/teaching.md'
    - Cours de Logique: 'https://adurier.github.io/logic-course'
    - Cours de Programmation Fonctionnelle: 'https://adurier.github.io/func-prog'
  - Publications: 'publis.md'
  - A propos: 'about.md' 
not_in_nav: |
  /helper.md