name: ci
#From: https://github.com/jobindjohn/obsidian-publish-mkdocs
#Same on: https://squidfunk.github.io/mkdocs-material/publishing-your-site/
#See also, *if* useful: https://github.com/mhausenblas/mkdocs-deploy-gh-pages
on:
  push:
    branches:
      - dracula-theme
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-dracula-theme
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-obsidian-bridge
      - run: pip install mkdocs-callouts
#     - run: pip install mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force